### ISSUE TITLE
about export.py

### ISSUE THREAD

**Issue by coper16** [eric-yyjau/pytorch-superpoint#23]
Hi!
Thank you for your great work!!
I have a question about procedure (2).

I tried exporting detection on MS-COCO by GPU, but it is failed.
Do you know why it doesn't work?
No error, but tqdm bar doesn't progress.

![スクリーンショット 2020-08-14 1 12 28](https://user-images.githubusercontent.com/54351314/90159712-bf8cd980-ddcb-11ea-9840-2788bb2f4049.png)
![スクリーンショット 2020-08-14 1 13 24](https://user-images.githubusercontent.com/54351314/90159810-e2b78900-ddcb-11ea-8f03-0d849abffd55.png)

Now, I can exporting by CPU.

**Comment by eric-yyjau** [comment]
Hi @coper16 ,
Thank you for raising this issue.
I'm not sure why. I tested with KITTI dataset just now and it worked ok with GPU.
Is it because of too many dataloader workers?
https://github.com/eric-yyjau/pytorch-superpoint/blob/4ff74df8fa3c10ce9eb9fdc561f787d9e8bc9691/configs/magicpoint_coco_export.yaml#L31
You can try to set it to 0.

**Comment by coper16** [comment]
Thank you for your quick reply.
I tried changing workers_test parameter(2 to 0) and  it worked well!

Thank you very much.
