### ISSUE TITLE
Sub-pixel

### ISSUE THREAD

**Issue by ppinheiro2** [eric-yyjau/pytorch-superpoint#38]
Hi,
I've been implementing Superpoint and got good results. However I found your repo now and I've seen that you use Sub-pixel. Are you using sub-pixel in the coordinates of the detected keypoints? Could you briefly explain how you do that?
Have you noticed improvements in homography estimation errors?

Best regards,
Pedro

**Comment by eric-yyjau** [comment]
Hi @ppinheiro2 

Thank you for your questions.
Good to know you're also working on this.

You can refer to sec 3.B in our paper (https://arxiv.org/pdf/2007.15122.pdf).
We are using subpixel to make the gradient flow from the keypoints.

The subpixel is estimated when we get the keypoint.
However, it is not helping much in the homography estimation.
I think the reason is that the keypoints and correspondences are trained using sampled homography.
The signal of keypoints may be noise.

Hope that helps. Thanks.

You-Yi
