### ISSUE TITLE
Loader.py error

### ISSUE THREAD

**Issue by eminerkol-60** [eric-yyjau/pytorch-superpoint#58]
Hi, I am currently trying to use synthetic dataset for the homography adaptation task and I am getting the error below;
Traceback (most recent call last):
  File "export.py", line 409, in <module>
    args.func(config, output_dir, args)
  File "/home/hmahmad/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "export.py", line 243, in export_detector_homoAdapt_gpu
    data = dataLoader(config, dataset=task, export_task=export_task)
  File "/home/hmahmad/Desktop/Emin/pytorch-superpoint-master/utils/loader.py", line 105, in dataLoader_test
    from datasets.SyntheticDataset import SyntheticDataset
ImportError: cannot import name 'SyntheticDataset'
there is no file called SyntheticDataset inside of the datasets folder. any help is appreciated.

Thanks.

**Comment by eric-yyjau** [comment]
Hi @eminerkol-60,

I think there's a bug there.
If I remember correctly, you'll train magicPoint from synthetic dataset with this config.
https://github.com/eric-yyjau/pytorch-superpoint/blob/4ff74df8fa3c10ce9eb9fdc561f787d9e8bc9691/configs/magicpoint_shapes_pair.yaml#L3

This will import dataload from `SyntheticDataset_gaussian` instead of `SyntheticDataset`.
The error and code you show should be cleaned up.
If you have an update, feel free to submit a pull request.

Thanks.
